---
# Пакеты для установки через pacman
pacman_packages:
  - linux-zen
  - flatpak
  - fwupd
  - git
  - base-devel
  - ffmpeg
  - gst-plugins-base
  - gst-plugins-good
  - gst-plugins-bad
  - gst-plugins-ugly
  - libva-mesa-driver
  - gst-libav
  - aom
  - dav1d
  - libwebp
  - flac
  - opus
  - libavif
  - libheif
  - libvpx
  - tmux
  - btop
  - vlc
  - wget
  - curl
  - duperemove
  - neovim
  - gamescope
  - lutris
  - steam
  - steam-devices 
  - gamemode
  - less
  - spotify-launcher
  - tuned
  - tuned-ppd
  - cups
  - splix
  - obs-studio
  - obsidian
  - pacman-contrib
  - tldr
  - snapper
  - blanket
  - apparmor
  - grub-btrfs
  - inotify-tools
  - libva-mesa-driver
  - lib32-libva-mesa-driver
  - fish
  - dnsutils
  - iputils
  - whois
  - adobe-source-sans-fonts
  - adobe-source-serif-fonts
  - adobe-source-code-pro-fonts
  - noto-fonts-emoji
  - ttf-ubuntu-font-family
  - inter-font
  - ttf-liberation
  - ttf-dejavu
  - mangohud
  - nftables
  - firewalld
  - rustup
  - ripgrep
  - firewall-config
  - ttf-jetbrains-mono-nerd
  - adobe-source-han-sans-jp-fonts
  - adobe-source-han-serif-jp-fonts
  - noto-fonts-cjk
  - 7zip
  - openssh

# Пакеты для установки через AUR (с помощью yay)
aur_packages:
  - btrfs-assistant
  - brave-bin
  - visual-studio-code-bin
  - spotx-git
  - arch-update

# Пакеты для установки через Flatpak
flatpak_packages:
  - com.vysp3r.ProtonPlus
  - com.heroicgameslauncher.hgl

# Пакеты, которые нужно удалить
remove_packages:
  - firefox
  - htop
  - epiphany
  - totem
  - gnome-tour
  - snapshot
  - gnome-maps
  - rhythmbox
  - gnome-music
  - showtime
  - gnome-boxes
  - gnome-console
  - evolution
  - vim
  - vim-runtime
  - decibels
  - gnome-software

# Системные сервисы для включения и запуска
enable_services:
  - tuned
  - tuned-ppd
  - paccache.timer
  - firewalld
  - apparmor
  - grub-btrfsd
  - sshd

kde_settings:
  - { file: plasma-localerc, group: Language, key: Language, value: 'ru:en' }
  - { file: plasma-localerc, group: Formats, key: LANG, value: 'ru_RU.UTF-8'}
  - { file: kxkbrc, group: Layout, key: LayoutList, value: 'us,ru' }
  - { file: kxkbrc, group: Layout, key: Use, value: true }
  - { file: kxkbrc, group: Layout, key: VariantList, value: ','}
  - { file: kxkbrc, group: Layout, key: ResetOldOptions, value: true }
  - { file: kxkbrc, group: Layout, key: ShowLayoutIndicator, type: bool, value: false }
  - { file: kxkbrc, group: Layout, key: Options, value: 'kpdl:dotoss,grp:alt_shift_toggle,grp:win_space_toggle' }
  - { file: kscreenlockerrc, group: Daemon, key: Autolock, value: false}
  - { file: powermanagementprofilesrc, group: AC, key: TurnOffDisplayIdleTimeoutSec, value: 0}
  - { file: powermanagementprofilesrc, group: Display, key: TurnOffDisplayIdleTimeoutSec, value: 0}
  - { file: kcminputrc, group: Keyboard, key: NumLock, value: 0}
  - { file: sddm.conf, group: General, key: Numlock, value: 'on'}
  - { file: klaunchrc, group: BusyCursorSettings, key: Bouncing, value: false }
  - { file: klaunchrc, group: FeedbackStyle, key: BusyCursor, value: false }
  - { file: kwinrc, group: Plugins, key: shakecursorEnabled, value: false }
  - { file: plasmarc, group: OSD, key: kbdLayoutChangedEnabled, value: false }
  - { file: kdeglobals, group: General, key: font, value: 'Ubuntu,10,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: menuFont, value: 'Ubuntu,10,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: smallFont, value: 'Ubuntu,8,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: toolbarFont, value: 'Ubuntu,10,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: activeFont, value: 'Ubuntu,10,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: taskbarFont, value: 'Ubuntu,10,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: desktopFont, value: 'Ubuntu,10,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: fixed, value: 'JetBrainsMono Nerd Font,10,-1,5,50,0,0,0,0,0' }
  - { file: kdeglobals, group: General, key: XftAntialias, value: 'true' }
  - { file: kdeglobals, group: General, key: XftHinting, value: 'true' }
  - { file: kdeglobals, group: General, key: XftHintStyle, value: 'hintfull' }
  - { file: kdeglobals, group: General, key: XftSubPixel, value: 'rgb' }
  - { file: kwalletrc, group: Wallet, key: Enabled, value: false }

gnome_settings:
  - { group: "org.gnome.desktop.peripherals.mouse", key: "accel-profile", value: "'flat'" }
  - { group: "org.gnome.desktop.interface", key: "document-font-name", value: "'Ubuntu 11'" }
  - { group: "org.gnome.desktop.interface", key: "font-antialiasing", value: "'rgba'" }
  - { group: "org.gnome.desktop.interface", key: "font-hinting", value: "'full'" }
  - { group: "org.gnome.desktop.interface", key: "font-name", value: "'Ubuntu 11'" }
  - { group: "org.gnome.desktop.interface", key: "monospace-font-name", value: "'JetBrains Mono 11'" }
  - { group: "org.gnome.desktop.interface", key: "toolkit-accessibility", value: "false" }
  - { group: "org.gnome.desktop.peripherals.keyboard", key: "numlock-state", value: "true" }
  - { group: "org.gnome.desktop.peripherals.keyboard", key: "remember-numlock-state", value: "true" }
  - { group: "org.gnome.desktop.screensaver", key: "lock-enabled", value: "false" }
  - { group: "org.gnome.settings-daemon.plugins.housekeeping", key: "donation-reminder-enabled", value: "false" }
  - { group: "org.gnome.desktop.wm.preferences", key: "button-layout", value: "'appmenu:minimize,maximize,close'" }
  - { group: "org.gnome.shell", key: "enabled-extensions", value: "['background-logo@fedorahosted.org', 'dash-to-dock@micxgx.gmail.com', 'clipboard-indicator@tudmotu.com', 'ding@rastersoft.com']" }
  - { group: "org.gnome.desktop.input-sources", key: "mru-sources", value: "[('xkb', 'ru'), ('xkb', 'us')]" }
  - { group: "org.gnome.desktop.input-sources", key: "sources", value: "[('xkb', 'ru'), ('xkb', 'us')]" }
  - { group: "org.gnome.desktop.input-sources", key: "xkb-options", value: "['kpdl:dotoss', 'grp:alt_shift_toggle']" }
  - { group: "org.gnome.shell", key: "favorite-apps", value: "['brave-browser.desktop', 'obsidian.desktop', 'md.obsidian.Obsidian.desktop', 'spotify-launcher.desktop', 'com.spotify.Client.desktop', 'steam.desktop', 'code.desktop', 'com.obsproject.Studio.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop', 'org.gnome.TextEditor.desktop', 'org.gnome.Calculator.desktop']" }
  - { group: "org.gnome.system.locale", key: "region", value: "'ru_RU.UTF-8'" }


gnome_packages:
  - ptyxis
  - extension-manager
  - gnome-firmware
  - seahorse

gnome_aur_packages:
  - xdg-terminal-exec
  - nautilus-open-in-ptyxis

kde_packages:
  - sddm-kcm
  - breeze
  - breeze-cursors
  - breeze-gtk
  - breeze-icons
  - kwalletmanager

kde_aur_packages:
  - konsave